version: 0.0
os: linux

files:
  - source: ./ROOT.war
    destination: /opt/tomcat/webapps

hooks:
  BeforeInstall:
    - location: scripts/applicationStop.sh
      timeout: 900
      runas: centos
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 900
      runas: centos
  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 900
      runas: centos
