version: 0.0
os: linux
files:
  - source: ./noteapp-0.0.1-SNAPSHOT.war
    destination: /opt/tomcat/webapps
hooks:
  BeforeInstall:
    - location: scripts/applicationStop.sh
      timeout: 900
      runas: centos
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 900
      runas: centos
  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 900
      runas: centos
