version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/openjdk:8u181-jdk-stretch
    working_directory: ~/project/webapp
jobs:
  build-app:
    executor: my-executor
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    parameters:
      profile-name:
        description: Profile name
        type: string
        default: "default"
      aws-access-key-id:
        description: AWS access key id for IAM role
        type: env_var_name
        default: AWS_ACCESS_KEY
      aws-secret-access-key:
        description: AWS secret key for IAM role
        type: env_var_name
        default: AWS_SECRET_KEY
      aws-region:
        description: AWS region
        type: env_var_name
        default: AWS_REGION
      bucket-name:
        description: Artifact holder Bucket Name
        type: env_var_name
        default: AWS_CODE_DEPLOY_BUCKET
    steps:
      - checkout:
          path: ~/project
      # Configure aws cli
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: Install awscli
          command: |
            sudo apt install apt-utils -y
            sudo apt-get install python3 -y
            sudo apt install python3-pip -y
            sudo pip3 install awscli
      - run:
          name: Configure AWS Access Key ID
          command: |
            aws configure set aws_access_key_id \
            $<< parameters.aws-access-key-id >> \
            --profile << parameters.profile-name >>
      - run:
          name: Configure AWS Secret Access Key
          command: |
            aws configure set aws_secret_access_key \
            $<< parameters.aws-secret-access-key >> \
            --profile << parameters.profile-name >>
      - run:
          name: Configure AWS region
          command: |
            aws configure set region $<< parameters.aws-region >> \
            --profile << parameters.profile-name >>
      # Install aws code deploy
      - run:
          name: Install aws code deploy
          command: |
            # Ruby dep
            sudo mkdir -p /etc/apt/sources.list.d
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C3173AA6
            cat <<EOF | sudo tee /etc/apt/sources.list.d/brightbox-ubuntu-ruby-ng-wily.list
            deb http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu wily main
            EOF
            sudo apt-get update
            sudo apt-get install ruby2.0
            cd
            wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
            chmod +x ./install
            sudo ./install auto
            sudo service codedeploy-agent start
      # Download and cache dependencies
      - restore_cache:
          keys: 
            - m2-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - m2-
      - run:
          name: Download maven dependency
          command: mvn dependency:go-offline dependency:resolve-plugins
      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}
      - run:
          name: zip up artifacts if tests are successful
          command: |
            mvn integration-test
            [[ $? -eq 0 ]] || exit 1
            rm -rf ~/artifacts
            mkdir ~/artifacts
            cd ~/artifacts
            cp ~/project/webapp/target/*.war ~/artifacts
            cp ~/project/infrastructure/aws/codedeploy/*.sh ~/artifacts
            zip -r ~/csye6225-webapp.zip ~/artifacts
            ls -al; pwd
      - run:
          name: Deploy to S3
          command: |
            aws deploy create-application --application-name csye6225-webapp
            aws deploy push \
              --application-name csye6225-webapp \
              --s3-location $<< parameters.bucket-name >> \
              --ignore-hidden-filescp ~/artifacts.zip 
workflows:
  version: 2
  configure-and-build:
    jobs:
      - build-app:
          filters:
            # TODO: change branch 
            branches:
              only:
                - assignment5